<a href="https://colab.research.google.com/github/dinhquy-nguyen-1704/Weekly_exercise/blob/main/Vector_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def computeVectorLength(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

In [3]:
# EXERCISE 1
vector = np.array([-2, 4, 9, 21])
result = computeVectorLength([vector])
print(round(result,2))

23.28


In [4]:
def computeDotProduct(vector1, vector2):
  result = vector1.T @ vector2
  return result

In [5]:
# EXERCISE 2
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = computeDotProduct(v1, v2)
print(round(result,2))

4


In [6]:
# EXERCISE 3
x = np.array([[1, 2],
[3, 4]])
k = np.array([1, 2])
print('result \n', x.dot(k))

result 
 [ 5 11]


In [7]:
# EXERCISE 4
x = np.array([[-1, 2], [3, -4]])
k = np.array([1, 2])
print('result \n', x@k)

result 
 [ 3 -5]


In [8]:
def matrix_multi_vector(matrix, vector):
    result = matrix @ vector
    return result

In [9]:
# EXERCISE 5
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [10]:
def matrix_multi_matrix(matrix1, matrix2):
    result = matrix1 @ matrix2
    return result

In [11]:
# EXERCISE 6
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3],[6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [12]:
# EXERCISE 7
m1 = np.eye(3)
m2 = np.array([[1, 1, 1],[2, 2, 2], [3, 3, 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [13]:
# EXERCISE 8
m1 = np.eye(2)
m1 = np.reshape(m1,(-1,4))[0]
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [14]:
# EXERCISE 9
m1 = np.array([[1, 2], [3, 4]])
print(np.reshape(m1,(-1,4), "F"))
m1 = np.reshape(m1,(-1,4), "F")[0]
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)
print(type(result))

[[1 3 2 4]]
[29 29 29 29]
<class 'numpy.ndarray'>


In [15]:
def inverse_matrix(matrix):
  det = np.linalg.det(matrix)
  m = np.array([[matrix[1][1], -matrix[0][1]], [-matrix[1][0], matrix[0][0]]])
  if det != 0:
    result = (1/det)*m
  else:
    result = None
  return result

In [16]:
# EXERCISE 10
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [17]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues,eigenvectors = np.linalg.eig(matrix)
    return eigenvalues,eigenvectors

In [18]:
# EXERCISE 11
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [19]:
def compute_cosine(v1, v2):
  tich_vo_huong = v1.T @ v2
  cos_sin = tich_vo_huong/(np.linalg.norm(v1)*np.linalg.norm(v2))
  return cos_sin

In [20]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))

0.577
